// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  anchor: dynamic(() => import("./Anchor")),
  archive: dynamic(() => import("./Archive")),
  contact_form: dynamic(() => import("./ContactFormVrijwilliger")),
  contact_form_sponsor: dynamic(() => import("./ContactFormSponsor")),
  contact_form_validated: dynamic(() => import("./ContactFormGast")),
  content_cards: dynamic(() => import("./ContentCards")),
  contentcard: dynamic(() => import("./InfoCards")),
  faq: dynamic(() => import("./Faq")),
  i_frame: dynamic(() => import("./IFrame")),
  info_form: dynamic(() => import("./InfoForm")),
  latest_news: dynamic(() => import("./LatestNews")),
  logos: dynamic(() => import("./Logos")),
  section: dynamic(() => import("./Section")),
  text_block: dynamic(() => import("./TextBlock")),
};
